### ISSUE TITLE
Unused variable `q_embed` in the Llama's `preprocess_query` method

### ISSUE THREAD

**Issue by jake-seunghyukoh** [abertsch72/unlimiformer#31]
Hi, while reviewing the `UnlimiformerLLaMa` class, I found an [unused variable](https://github.com/abertsch72/unlimiformer/blob/181a9b519dbd9fea2bb2198c3a9d930c52769d43/src/unlimiformer.py#L1089C9-L1089C16) in the `preprocess_query` method.

The variable `q_embed` looks quite important since it's related to Llama's rotary embedding. Is this intentional?

Thanks!

**Comment by urialon** [comment]
Hi @jake-seunghyukoh ,
Thank you for your interest in our work and for reporting this!

This unused variable practically lead the model to use `position==0` for the query.
This was fixed in https://github.com/abertsch72/unlimiformer/commit/60b4316d524e19b52ebba3954af75d6fa07b84a9

Thanks again, let us know if you have any more questions!

Best,
Uri
